# Permalinks
permalink:           pretty

# Setup
title:               Nino
tagline:             my logbook
url:                 https://ninomllr.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nino Müller
  url:               https://twitter.com/ninmllr
  email:             nino.mueller@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
